Update terraform-e2e.yml

diff --git a/.github/workflows/terraform-e2e.yml b/.github/workflows/terraform-e2e.yml
--- a/.github/workflows/terraform-e2e.yml
+++ b/.github/workflows/terraform-e2e.yml
@@ -17,9 +17,23 @@ jobs:
 
       - name: Install Kind & Kubectl
         run: |
-          curl -LO "https://kind.sigs.k8s.io/dl/v0.23.0/kind-linux-amd64"
-          chmod +x kind
-          mv kind /usr/local/bin/kind
+          for i in {1..3}; do
+            curl -LO "https://kind.sigs.k8s.io/dl/v0.23.0/kind-linux-amd64"
+            if [ $? -eq 0 ]; then
+              chmod +x kind
+              mv kind /usr/local/bin/kind
+              break
+            else
+              echo "Failed to download Kind. Retrying..."
+              sleep 10
+            fi
+          done
+
+          if [ $? -ne 0 ]; then
+            echo "Failed to download and install Kind after multiple retries."
+            exit 1
+          fi
+
           curl -LO "https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl"
           chmod +x kubectl
           mv kubectl /usr/local/bin/kubectl
